version: '3'

services:
  resume:
    build:
      context: .
      dockerfile: .docker/resume.dockerfile
    volumes:
      - ./styles:/app/styles
      - ./output:/output
    environment:
      - OUT_DIR=/output
    command: all # Default to building all formats (pdf, html, docx, rtf)
    # Alternative commands: pdf, html, docx, rtf
