version: '3'

services:
  resume:
    build:
      context: .
      dockerfile: .docker/resume.dockerfile
    volumes:
      - ./output:/app/output
    # Default to generating PDF
    command: pdf

# Add usage examples as comments for quick reference
# Usage:
# docker-compose run resume clean     # Clean output directory
# docker-compose run resume pdf       # Generate PDF
# docker-compose run resume clean-pdf # Clean and generate PDF
