version: '3'

services:
  resume:
    build:
      context: .
      dockerfile: .docker/resume.dockerfile
    volumes:
      - ./:/app/
    # Default to showing usage help
    command: help

# Usage examples:
# Basic commands:
#   docker-compose run resume latex /app/templates/resume.tex           # Generate PDF with default output name
#   docker-compose run resume latex /app/templates/resume.tex cv       # Generate PDF with custom output name
#   docker-compose run resume clean                                    # Clean output directory
#   docker-compose run resume clean-latex /app/templates/resume.tex    # Clean and generate PDF
#
# Examples with different input files:
#   docker-compose run resume latex /app/templates/cv.tex              # Generate from cv.tex
#   docker-compose run resume latex /app/templates/cover-letter.tex    # Generate from cover-letter.tex
#
# Help:
#   docker-compose run resume help                                     # Show usage instructions
