# action.yml
name: 'Texlive Build'
description: 'Build a document using texlive'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/mszep/pandoc_resume/resume_builder:latest'
  entrypoint: 'make pdf'
