# This workflow updates the docker container which has context and
# pandoc installed, and on which the resume documents are built. The
# workflow runs whenever the dockerfile is changed, and updates the
# container image in the Github Packages registry.

name: Publish Docker Image

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # This workflow contains a single job which does both the building and the pushing
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: mszep/pandoc_resume/resume_builder
          tag_with_ref: true
          dockerfile: .docker/resume.dockerfile
