# This is a basic workflow to help you get started with Actions

name: build-resume

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-resume:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Install ConTeXt
        run: |
          sudo apt-get update
          sudo apt-get install -y context

      - name: Build PDF Resume
        run: |
          make pdf

      - name: Upload Resume PDF
        uses: actions/upload-artifact@v4
        with:
          name: Resume PDF
          path: output/*.pdf

